import { GoogleGenerativeAI } from "@google/generative-ai";
import { NextResponse } from "next/server";

const genAI = new GoogleGenerativeAI(process.env.GEMINI_APIKEY as string);

export async function POST (request : Request) {
    try {
        const { text } = await request.json();

        const model = genAI.getGenerativeModel({
            model : "gemini-2.5-flash",
            generationConfig: { responseMimeType: "application/json" }
        });

        const prompt = `You are an advanced AI-generated text detection system specialized in analyzing academic and scientific writing.

                        The input text is part of a scientific research paper (for example: abstract, introduction, methodology, results, discussion, or conclusion).

                        Your task is to estimate the likelihood that the text was written by a human or generated by an AI system.

                        You must perform a deep linguistic and stylistic analysis of the entire text before producing your final estimation.

                        Important context:

                        Academic writing often follows formal and structured conventions. Therefore, the presence of formal language, academic transitions, or structured paragraphs alone MUST NOT be considered strong evidence of AI generation.

                        Only assign a high AI probability when multiple indicators appear simultaneously.

                        You must analyze the text using the following signals.

                        PERPLEXITY-LIKE ANALYSIS  
                        Evaluate how predictable the wording and phrasing are.  
                        AI-generated text tends to have highly predictable language patterns with lower linguistic surprise.

                        BURSTINESS ANALYSIS  
                        Measure the variation in sentence length and structure.  
                        Human writing typically shows irregular variation, while AI writing often shows smoother patterns.

                        SENTENCE STRUCTURE UNIFORMITY  
                        Check whether sentences follow repetitive grammatical structures or templates.

                        VOCABULARY RICHNESS  
                        Evaluate whether the vocabulary shows nuanced usage, domain depth, and variation.

                        REPETITION PATTERNS  
                        Detect repeated transitions or template-like academic phrases such as:

                        - Furthermore
                        - Moreover
                        - In conclusion
                        - It is important to note that
                        - Consequently

                        CONTEXTUAL DEPTH  
                        Assess whether the text contains deep reasoning, nuanced explanation, or only generic academic statements.

                        STRUCTURAL PATTERNS  
                        Evaluate whether paragraphs follow overly balanced or predictable structures.

                        You must analyze the ENTIRE text first, then perform paragraph-level and sentence-level analysis.

                        Return the result strictly in JSON format.

                        JSON STRUCTURE

                        {
                        "overall_ai_probability": number (0-100),
                        "human_probability": number (0-100),
                        "confidence": number (0-100),
                        "risk_level": "low | medium | high | very_high",

                        "metrics": {
                            "perplexity_score": number (0-1),
                            "burstiness_score": number (0-1),
                            "sentence_uniformity_score": number (0-1),
                            "repetition_score": number (0-1),
                            "vocabulary_richness_score": number (0-1)
                        },

                        "analysis": {
                            "perplexity_analysis": "explanation",
                            "burstiness_analysis": "explanation",
                            "structure_analysis": "explanation",
                            "vocabulary_analysis": "explanation",
                            "context_depth_analysis": "explanation"
                        },

                        "paragraph_analysis": [
                            {
                            "paragraph_index": number,
                            "ai_probability": number,
                            "risk_level": "low | medium | high",
                            "reason": "short explanation"
                            }
                        ],

                        "suspected_sentences": [
                            {
                            "text": "original sentence",
                            "ai_probability": number,
                            "reason": "why this sentence appears AI-like"
                            }
                        ],

                        "human_indicators": [
                            "signals suggesting human writing"
                        ],

                        "ai_indicators": [
                            "signals suggesting AI generation"
                        ],

                        "summary": "overall explanation of the result"
                        }

                        Rules:

                        - human_probability = 100 - overall_ai_probability
                        - confidence indicates reliability of the estimation.
                        - risk_level mapping:

                        0–20 → low  
                        21–40 → medium  
                        41–70 → high  
                        71–100 → very_high

                        - paragraph_analysis must evaluate each paragraph individually.
                        - suspected_sentences must include the most suspicious sentences (maximum 5).
                        - If no suspicious sentences exist, return an empty array.

                        IMPORTANT:

                        Return ONLY valid JSON.  
                        Do NOT include markdown formatting, comments, or explanations outside the JSON.

                        TEXT TO ANALYZE:

                        ${ text }
                        `;

        const result = await model.generateContent(prompt);
        let responseText = await result.response.text();
        responseText = responseText.replace(/```json|```/g, "").trim();

        try {
            const jsonData = JSON.parse(responseText);
            return NextResponse.json(jsonData);
        } catch (parseError) {
            console.error("Lỗi Parse JSON. Nội dung thô từ AI:", responseText);
            return NextResponse.json({ 
                error: "Dữ liệu AI trả về không đúng định dạng",
                raw: responseText 
            }, { status: 500 });
        }
    }
    catch (error : any) {
        console.error("Gemini Error:", error);
        return NextResponse.json({ error: "Không thể xử lý văn bản" }, { status: 500 });
    }
}